# Generated by Django 3.2.5 on 2021-12-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('_class', models.CharField(choices=[('SPAM', 'SPAM'), ('HAM', 'HAM')], max_length=4)),
            ],
        ),
    ]
